# Generated by Django 2.2.28 on 2023-08-31 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xranking', '0003_auto_20230831_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectquery',
            name='query',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='xranking.Query'),
        ),
    ]
